import styles from "../FAQ.module.css";

export default function WhyLeverage() {
  return (
    <div>
      <div className={styles.faqAnswer}>
      A Partner Account promotes dive trips by turning diver sightings, sea life data, and reviews into live, seasonally relevant content that <strong>strengthens your trip listings.</strong>
      </div>

      <div style={{ height: 20 }} />

      <div className={styles.faqAnswer}>
      This is achieved through two key steps.
      </div>

      <div style={{ height: 20 }} />

      <div className={styles.faqAnswer}>
      First, encourage divers on your trips to use the app to submit their sea life sightings and dive site reviews. This <strong>creates a continuous stream of authentic, up-to-date content generated by divers</strong> who have firsthand experience at your sites.
      </div>

      <div style={{ height: 20 }} />

      <div className={styles.faqAnswer}>
      Second, use the <strong>Trip Creator—an exclusive Partner Account feature</strong>—to build trip listings. Because trips are linked to specific dive sites, your listings automatically incorporate relevant sightings and reviews, allowing you to promote your trips using real, seasonally relevant experiences.
      </div>

      <div style={{ height: 20 }} />

      <div className={styles.faqAnswer}>
      With a small initial effort, this approach creates a <strong>self-renewing content cycle</strong> where diver participation continuously strengthens your trip listings and increases their appeal to future divers.
      </div>
    </div>
  );
}









